agmarr/agmar/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static
from django.conf import settings
from ofertownik import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ofertownik/',include('ofertownik.urls',namespace="ofertownik")),
    path('',views.IndexView.as_view(),name="index"),
    path('eng',views.TemplateView.as_view(),name="english"),
    path('user_login',views.user_login,name="user_login"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agmarr/ofertownik/urls.py
from django.urls import path
from . import views
app_name = 'ofertownik'
urlpatterns = [
    path('add',views.create_offer,name="createoffer"),
    path('<slug:slug>/',views.OfferDetailView.as_view(),name="viewoffer"),
    path('<slug:slug>/edit',views.edit_offer,name="editoffer"),
    path('offers',views.OfferListView.as_view(),name="offerlist"),
    path('addproduct',views.addproduct,name='addproduct'),
    path('deleteproduct',views.deleteproduct,name='deleteproduct'),
    path('editproduct',views.editproduct,name='editproduct'),
    path('deleteimage/<int:pk>',views.deleteimage,name='deleteimage'),
    path('product/<int:pk>/addimage',views.addimage,name='addimage'),
    path('send_email',views.send_email,name='sendmail'),


]

agmarr/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    {% block extra_title %}{% endblock %}

    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet">
    <script
  src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">



<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<style media="screen">



</style>
  </head>
  <body>

<div class="workspace">



          {% block body_block %}
              {% endblock %}
</div>
      <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
  </body>

</html>

agmarr/templates/eng.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <title>Agmar - gadżety reklamowe</title>
  <meta name="keywords" content="gadżety, upominki, reklamowe, logo, prezenty, biurowe, agmar, pphagmar, akcesoria, artykuły, agencja, odzież, zestawy, systemy, wystawiennicze, migające, scherrer, titan, reklamowa, elektronika, zabawki, kuchenne, torby, breloki, światłowody ">
<meta name="description" content="Agmar - Agencja reklamowa - szeroka oferta upominków reklamowych
Gadżety i upominki reklamowe - sklep on-line (duże rabaty!), markowe prezenty w specjalnych cenach, biurowe, ekskluzywne, firmowe, promocyjne, torby, parasole, długopisy i inne upominki  ">
  <link href="https://fonts.googleapis.com/css?family=Crimson+Text|Archivo|Amaranth|Roboto:300,700" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" type="text/css" media="(max-device-width: 768px)" href="{% static 'css/style.css' %}" />
  <script
src="https://code.jquery.com/jquery-3.5.1.min.js"
integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
crossorigin="anonymous"></script>
	<title>Agmar</title>
  <style>
    body {background-color: #f7f7f7;border:0;margin: 0 0;align-items: flex-start;font-weight: 400;font-size:18px;font-family: 'Roboto', sans-serif;  }
  </style>
</head>
<body>
	<header>
		<div id="navbar">
			<img class="logo-main" src="{% static 'img/loggo2.png' %}">
      <a class="lang" href="{% url 'index' %}">EN/pl</a>
			<a class="nav-item" href="#form-anchor">Contact</a>
			<a class="nav-item" href="#katalogi-anchor">Offer</a>
			<a class="nav-item" href="#standy-anchor">About</a>
		</div>
	</header>
	<main>
		<div class="blok1" id="photo2">
		<div class="insid"><h1>Give a shape to your brand!</h1>
		<a href="#katalogi-anchor"><button>See the offer</button></a></div>
		</div>
		<div class="blok2" id="standy">
      <a class="anchor" id="standy-anchor"></a>
			<div class="stand">
				<p>We are a small company. Thanks to that we can spend more time on customer service and focus on quick realization process for your order, maximizing your satisfaction!</p><br>
				<a href="#standy-anchor"><button>About</button></a>
			</div>
			<div class="stand">
				<p>Did you already choose the product to promote your brand?
          You can come to us with a ready idea, which we will fulfill quickly and with low cost. But you only need the desire to promote your company - we will choose the best product for your edeavor!</p>
				<a href="#katalogi-anchor"><button>Offer</button></a>
			</div>
			<div class="stand">
				<p>Contact us today!
          We offer a quick and complete customer service. We accompany you from the very begining - to control wether every step of our cooperation is up to your liking!</p><br>
				<a href="#form-anchor"><button>kontakt</button></a>
			</div>
		</div>
		<div class="blok1" id="photo3">
    <div class="insid"><h1>Our mission is for you to be seen</h1></div></div>
		<div class="blok2">Our company works on polish promotional market since 1997. We cooperate with many known distributors and producers of advertising gadgets. Thanks to that we can offer a wide arrangement of quality products at competetive prices as well as quick and professional service. We provide various encrusting techniques.</div>
		<div class="blok1" id="photo4">
</div>
		<div class="blok2">
            <a class="anchor" id="katalogi-anchor"></a>
            We invite you to get aquanted with our rich offer of promotional articles.

Advertising gifts offered by us are always of high quality and fulfilment of the order is always on time. That is why we gained trust of wide range of customers.

We sincerely invite you to try our services!
<br>
To check out our offer, click one of our many partners catalogues below or contact us directly.
</div>
		<div class="blok2" id="katalogi">

			<a href="http://www.voyager-katalog.pl/"><img src="{% static 'img/voyager.jpg' %}"></a>
			<a href="http://www.its-easy-now.tiphost.net/pl-dc36c49becdf/agmar"><img src="{% static 'img/easygifts.gif' %}"></a>
      <a href="https://promotiontops.pl/"><img src="{% static 'img/tops.jpg' %}"></a>
      <br>
			<a href="https://www.mojesystemy.pl/AGMAR/groups/systemy_rolowane"><img src="{% static 'img/kento.jpg' %}"></a>

			<a href="https://noname.happygifts.eu/?embed=w6AWaCyv8XExWml4Y2BA"><img src="{% static 'img/lecce.png' %}" style="background-color:gray;"></a>

			<a href="http://www.royaldesign.pl/"><img rc="{% static 'img/logo Royal.png' %}"></a>
			<a href="https://agmar.bluecollection.gifts/"><img src="{% static 'img/blue.jpg' %}"></a>
		</div>



		<div class="blok1" id="form">
      <a class="anchor" id="form-anchor"></a>
      <form name="contactform" method="POST" >
          {% csrf_token %}
<table width="450px">
<tr>
 <td valign="top">
  <label for="first_name">Name *</label>
 </td>
 <td valign="top">
  <input  type="text" name="first_name" maxlength="50" size="30" required>
 </td>
</tr>
<tr>
 <td valign="top">
  <label for="last_name">Surname *</label>
 </td>
 <td valign="top">
  <input  type="text" name="last_name" maxlength="50" size="30" required>
 </td>
</tr>
<tr>
<td valign="top">
 <label for="template">Subject *</label>
</td>
<td valign="top">
 <input  type="text" name="subject" maxlength="50" size="30" required>
</td>
</tr>

<tr>
 <td valign="top">
  <label for="email">E-mail Adress *</label>
 </td>
 <td valign="top">
  <input  type="text" name="email" maxlength="80" size="30" required>
 </td>
</tr>
<tr>
 <td valign="top">
  <label for="telephone">Telephone number</label>
 </td>
 <td valign="top">
  <input  type="text" name="telephone" maxlength="30" size="30">
 </td>
</tr>
<tr>
 <td valign="top">
  <label for="comments">Message *</label>
 </td>
 <td valign="top">
  <textarea  name="comments" maxlength="1000" cols="25" rows="6"></textarea>
 </td>
</tr>
<tr>
 <td colspan="2" style="text-align:center">
  <input id="mmail" class="contact-form" type="submit" value="Wyślij">
 </td>
</tr>
</table>
</form>
<p id="contactt">

  P.P.H. AGMAR<br>
  Andrzej Pyzowski<br>
  ul. Łąkowa 22 <br>
  05-822 Milanówek<br>
  tel./fax +48 (22) 724 93 42<br>
  tel. kom. 608 018 335<br>
  </p>
    </div>
	</main>







<footer></footer>
      <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
 <script src="http://politykacookies.pl/politykacookies.js"></script>
 <script type="text/javascript">
   cookiesPolicy();










 </script>

</body>
</html>

agmarr/templates/index.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <title>Agmar - gadżety reklamowe</title>
  <meta name="keywords" content="gadżety, upominki, reklamowe, logo, prezenty, biurowe, agmar, pphagmar, akcesoria, artykuły, agencja, odzież, zestawy, systemy, wystawiennicze, migające, scherrer, titan, reklamowa, elektronika, zabawki, kuchenne, torby, breloki, światłowody ">
<meta name="description" content="Agmar - Agencja reklamowa - szeroka oferta upominków reklamowych
Gadżety i upominki reklamowe - sklep on-line (duże rabaty!), markowe prezenty w specjalnych cenach, biurowe, ekskluzywne, firmowe, promocyjne, torby, parasole, długopisy i inne upominki  ">
  <link href="https://fonts.googleapis.com/css?family=Crimson+Text|Archivo|Amaranth|Roboto:300,700" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" type="text/css" media="(max-device-width: 768px)" href="{% static 'css/style.css' %}" />
  <script
src="https://code.jquery.com/jquery-3.5.1.min.js"
integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
crossorigin="anonymous"></script>
	<title>Agmar</title>
  <style>
    body {background-color: #f7f7f7;border:0;margin: 0 0;align-items: flex-start;font-weight: 400;font-size:18px;font-family: 'Roboto', sans-serif;  }
  </style>
</head>
<body>
	<header>
		<div id="navbar">
			<img class="logo-main" src="{% static 'img/loggo2.png' %}">
      <a class="lang" href="{% url 'english' %}">PL/en</a>
			<a class="nav-item" href="#form-anchor">Kontakt</a>
			<a class="nav-item" href="#katalogi-anchor">Oferta</a>
			<a class="nav-item" href="#standy-anchor">O nas</a>
		</div>
	</header>
	<main>
		<div class="blok1" id="photo2">
		<div class="insid"><h1>Nadaj kształt swojej marce!</h1>
		<a href="#katalogi-anchor"><button>Zobacz ofertę</button></a></div>
		</div>
		<div class="blok2" id="standy">
      <a class="anchor" id="standy-anchor"></a>
			<div class="stand">
				<p>Jesteśmy małą firmą, dzięki czemu możemy poświęcić więcej czasu na obsługę klienta i zadbanie o to by proces realizacji zamówienia był jak najkrótszy, a Twoja satysfakcja - największa!</p><br>
				<a href="#standy-anchor"><button>O nas</button></a>
			</div>
			<div class="stand">
				<p>Masz już wybrany produkt promujący Twoją markę?
				Możesz przyjść do nas z gotowym pomysłem, który zrealizujemy w jak najniższej cenie, ale wystarczy sama chęć promocji firmy - wybierzemy najbardziej pasujące produkty do Twojej firmy!</p>
				<a href="#katalogi-anchor"><button>Oferta</button></a>
			</div>
			<div class="stand">
				<p>Skontaktuj się z nami już dzisiaj!
				Oferujemy szybką i kompleksową obsługę klienta. Jesteśmy z Tobą od samego początku - kontrolując czy na każdym etapie naszej współpracy jesteś zadowolony z naszej pracy!</p><br>
				<a href="#form-anchor"><button>kontakt</button></a>
			</div>
		</div>
		<div class="blok1" id="photo3">
    <div class="insid"><h1>Naszą misją jest to, byś został zauważony</h1></div></div>
		<div class="blok2">Nasza Firma działa na rynku polskim w branży reklamowej od 1997 roku. Współpracujemy z wieloma Dystrybucjami i wieloma Producentami gadżetów reklamowych, dzięki czemu możemy zagwarantować szeroki asortyment produktów, ich dobrą jakość przy konkurencyjnych cenach oraz szybką i fachową obsługę. Zapewniamy zdobienie gadżetów różnymi technikami.</div>
		<div class="blok1" id="photo4">
</div>
		<div class="blok2">
            <a class="anchor" id="katalogi-anchor"></a>
            Zapraszamy do zapoznania się z naszą bogatą ofertą artykułów promocyjnych.

Oferowane przez nas upominki są zawsze wysokiej jakości a zamówienia realizowane są na czas

i właśnie dlatego zdobyliśmy zaufanie wśród wielu klientów.

Serdecznie zapraszamy do skorzystania z naszych usług!<br>
Aby poznać naszą ofertę kliknij w jeden z katalogów naszych partnerów poniżej lub skontaktuj się z nami bezpośrednio.</div>
		<div class="blok2" id="katalogi">

			<a href="http://www.voyager-katalog.pl/"><img src="{% static 'img/voyager.jpg' %}"></a>
			<a href="http://www.its-easy-now.tiphost.net/pl-dc36c49becdf/agmar"><img src="{% static 'img/easygifts.gif' %}"></a>
      <a href="https://promotiontops.pl/"><img src="{% static 'img/tops.jpg' %}"></a>
      <br>
			<a href="https://www.mojesystemy.pl/AGMAR/groups/systemy_rolowane"><img src="{% static 'img/kento.jpg' %}"></a>

			<a href="https://noname.happygifts.eu/?embed=w6AWaCyv8XExWml4Y2BA"><img src="{% static 'img/lecce.png' %}" style="background-color:gray;"></a>

			<a href="http://www.royaldesign.pl/"><img rc="{% static 'img/logo Royal.png' %}"></a>
			<a href="https://agmar.bluecollection.gifts/"><img src="{% static 'img/blue.jpg' %}"></a>
		</div>



		<div class="blok1" id="form1">
      <a class="anchor" id="form-anchor"></a>
      <form name="contactform" id="myform" method="POST" >
          {% csrf_token %}
<table width="450px">
<tr>
 <td valign="top">
  <label for="first_name">Imię *</label>
 </td>
 <td valign="top">
  <input id="mailname" type="text" name="first_name" maxlength="50" size="30" required>
 </td>
</tr>
<tr>
 <td valign="top">
  <label for="last_name">Nazwisko *</label>
 </td>
 <td valign="top">
  <input  id="mailsurname" type="text" name="last_name" maxlength="50" size="30" required>
 </td>
</tr>
<tr>
<td valign="top">
 <label for="template">Temat *</label>
</td>
<td valign="top">
 <input id="mailsubject" type="text" name="subject" maxlength="50" size="30" required>
</td>
</tr>

<tr>
 <td valign="top">
  <label for="email">Adres Email *</label>
 </td>
 <td valign="top">
  <input id="mailsender"  type="text" name="email" maxlength="80" size="30" required>
 </td>
</tr>
<tr>
 <td valign="top">
  <label for="telephone">Numer telefonu</label>
 </td>
 <td valign="top">
  <input id="mailtelephone" type="text" name="telephone" maxlength="30" size="30">
 </td>
</tr>
<tr>
 <td valign="top">
  <label for="comments">Wiadomość *</label>
 </td>
 <td valign="top">
  <textarea id="mailmessage" name="comments" maxlength="1000" cols="25" rows="6"></textarea>
 </td>
</tr>
<tr>
 <td colspan="2" style="text-align:center">
  <input id="mmail" data-href="{% url 'ofertownik:sendmail' %}" class="contact-form" type="submit" value="Wyślij">
 </td>
</tr>
</table>
</form>
<p id="contactt">

  P.P.H. AGMAR<br>
  Andrzej Pyzowski<br>
  ul. Łąkowa 22 <br>
  05-822 Milanówek<br>
  tel./fax +48 (22) 724 93 42<br>
  tel. kom. 608 018 335<br>
  </p>
    </div>
	</main>







<footer></footer>
      <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
 <script src="http://politykacookies.pl/politykacookies.js"></script>
 <script type="text/javascript">
   cookiesPolicy();


 </script>

</body>
</html>

agmarr/templates/login.html
{% extends 'base.html' %}
{% block body_block %}
<div class="form-container">


<h1>Please log in</h1>
<form action="{% url 'user_login' %}" method="post">
  {% csrf_token %}
  <label for="username"></label>
<input type="text" name="username" placeholder="Login or Email adress" class="yolko" id="login-input">
<p><label for="password"></label>
<input type="password" name="password" class="yolko" placeholder="Password" id="password-input"></p>

<input type="submit" name="" value="login" id="login-btn">

</form>

</div>


<script>

      $(document).ready(function(){
         $("#guest").click(function(){
            console.log("11");
            document.getElementById('login-input').value = "1";
            document.getElementById('password-input').value = "1";
            document.getElementById("login-btn").click();



    });
  });






</script>
{% endblock %}