agmarr/agmar/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static
from django.conf import settings
from ofertownik import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ofertownik/',include('ofertownik.urls',namespace="ofertownik")),
    path('',views.IndexView.as_view(),name="index"),
    path('eng',views.TemplateView.as_view(),name="english"),
    path('user_login',views.user_login,name="user_login"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agmarr/ofertownik/urls.py
from django.urls import path
from . import views
app_name = 'ofertownik'
urlpatterns = [
    path('add',views.create_offer,name="createoffer"),
    path('<slug:slug>/',views.OfferDetailView.as_view(),name="viewoffer"),
    path('<slug:slug>/edit',views.edit_offer,name="editoffer"),
    path('offers',views.OfferListView.as_view(),name="offerlist"),
    path('addproduct',views.addproduct,name='addproduct'),
    path('deleteproduct',views.deleteproduct,name='deleteproduct'),
    path('editproduct',views.editproduct,name='editproduct'),
    path('deleteimage/<int:pk>',views.deleteimage,name='deleteimage'),
    path('product/<int:pk>/addimage',views.addimage,name='addimage'),
    path('send_email',views.send_email,name='sendmail'),


]

agmarr/ofertownik/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
from django.contrib.auth.models import User

from django.utils.crypto import get_random_string




def slug_save(obj):
    """ A function to generate a 5 character slug and see if it has been used and contains naughty words."""
    if not obj.slug: # if there isn't a slug
        obj.slug = get_random_string(5) # create one
        slug_is_wrong = True
    while slug_is_wrong: # keep checking until we have a valid slug
        slug_is_wrong = False
        other_objs_with_slug = type(obj).objects.filter(slug=obj.slug)
        if len(other_objs_with_slug) > 0:
            # if any other objects have current slug
            slug_is_wrong = True
        if slug_is_wrong:
            # create another slug and check it again
            obj.slug = get_random_string(5)

class Offer(models.Model):
    date_created = models.DateTimeField(default=timezone.now)
    title =  models.CharField(max_length=200)
    slug = models.SlugField(max_length=5,blank=True,)

    def __str__(self):
        return self.title


    def save(self, *args, **kwargs):
        slug_save(self) # call slug_save, listed below
        super(Offer, self).save(*args, **kwargs)


class Product(models.Model):
    offer = models.ForeignKey('ofertownik.Offer',on_delete=models.CASCADE,related_name='products')
    name = models.TextField(max_length=500,blank=True)
    price = models.TextField(max_length=500,blank=True)
    size = models.CharField(max_length=500,blank=True)
    material = models.TextField(max_length=500,blank=True)
    description = models.TextField(max_length=500,blank=True)
    link = models.TextField(max_length=None,blank=True)

    def __str__(self):
        return self.name
class ProductImage(models.Model):
    product = models.ForeignKey('ofertownik.Product',on_delete=models.CASCADE, related_name='images')
    adress = models.TextField(max_length=None)

agmarr/ofertownik/forms.py
from django import forms
from .models import Offer

class OfferForm(forms.ModelForm):
    class Meta():
        model = Offer
        fields = ['title']

agmarr/ofertownik/views.py
from django.shortcuts import render, get_object_or_404,redirect
import json
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import View,TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView,FormView
from .models import Offer,Product,ProductImage
from django.utils import timezone
from django.contrib import messages
from .forms import OfferForm
from . scraper import mainscrape
from django.http import JsonResponse
from django.core.mail import send_mail
from django.core.mail import EmailMessage
class IndexView(TemplateView):
    template_name = 'index.html'

class TemplateView(TemplateView):
        template_name = 'eng.html'
class OfferDetailView(DetailView):
    model = Offer


class OfferListView(ListView):
    model = Offer
    def get_queryset(self):
        return Offer.objects.order_by('-date_created')


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                messages.success(request, 'Your password was updated successfully!')
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('account no active')
        else:
            print('failed login detected')
            print('username: {} and password {}'.format(username,password))
            return HttpResponse('invalid login details supplied')

    else:
        return render(request,'login.html',{})



def create_offer(request):
    if request.method == 'POST':
        form = OfferForm(request.POST)


        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return redirect('ofertownik:editoffer', slug = instance.slug)
    else:
        form = OfferForm()
    return render(request, 'ofertownik/offerform.html', {'form': form})


def edit_offer(request,slug):
    context= {}
    offer = get_object_or_404(Offer,slug = slug)
    if request.method == 'POST' and request.is_ajax():
        pass
    else:
        offer = Offer.objects.get(slug = slug)
        context["offer"] = offer


        return render(request,'ofertownik/edit_offer.html',context)



def addproduct(request):
    if request.method == 'POST' and request.is_ajax():
        pk = json.loads(request.body).get('pk')
        print(pk)
        offer = get_object_or_404(Offer,pk=pk)
        print(request.body)
        choice = json.loads(request.body).get('choice')
        codelist = []
        codelist = json.loads(request.body).get('title').split(';')
        for e in codelist:
            prod = mainscrape(e,int(choice))
            instance = Product.objects.create(
                offer = offer,
                name = prod['title'],
                price = prod['price'],
                description = prod['description'],
                material = prod['material'],
                size = prod['size'],
                link = prod['link']
                )
            print(prod['link'])
            for r in prod['photos']:
                imageinstance = ProductImage.objects.create(
                    product = instance,
                    adress = r
                )
        return HttpResponse("OK")


def deleteproduct(request):
    if request.method == 'POST' and request.is_ajax():
        pk = json.loads(request.body).get('pk')
        product = get_object_or_404(Product,pk=pk)
        product.delete()
        return HttpResponse("OK")


def editproduct(request):
    if request.method == 'POST' and request.is_ajax():
        pk = json.loads(request.body).get('pk')
        prod = json.loads(request.body)
        print(prod)
        product = get_object_or_404(Product,pk=pk)
        product.name = prod['title']
        product.price = prod['price']
        product.description = prod['description']
        product.material = prod['material']
        product.size = prod['size']
        product.save()
        return HttpResponse("OK")


def deleteimage(request,pk):
    instance = get_object_or_404(ProductImage,pk=pk)
    offer = instance.product.offer
    slug = offer.slug
    instance.delete()
    return redirect('ofertownik:editoffer',slug = slug)


def addimage(request,pk):
    if request.method == 'POST' and request.is_ajax():
        product = get_object_or_404(Product,pk=pk)
        instance = ProductImage.objects.create(
                product = product,
                adress = json.loads(request.body).get('adress')
        )
        return HttpResponse("OK")


def send_email(request):
    if request.method == 'POST' and request.is_ajax():
        mail = json.loads(request.body)
        print(mail)
        name = mail['name']
        surname = mail['surname']
        subject = mail['subject']
        message = mail['message']
        telephone = mail['telephone']
        mailfrom = mail['mailfrom']
        msg = EmailMessage(
            subject,
            "Wiadomość od: " + name +' '+ surname +"<br>" + "Email: " + mailfrom + "<br>" + "Numer telefonu: " + telephone + "<br>" + "Wiadomość: "+ "<br>" + message,
            mailfrom,
            ['biuro@pphagmar.pl'],

            )
        msg.content_subtype = "html"
        msg.send()
        return HttpResponse("OK")

agmarr/ofertownik/templates/ofertownik/edit_offer.html
{% extends 'base.html' %}

{% block body_block %}
<div class="links">

<a class="btn btn-primary" href="{% url 'ofertownik:viewoffer' slug=offer.slug %}"target="_blank">Zobacz ofertę</a>
<a class="btn btn-primary" href="{% url 'ofertownik:offerlist'  %}"target="_blank">lista ofert</a>



</div>

<form id="form" method="POST" class="addproducts">
  {% csrf_token %}

        <div class="">
          add product/s
        </div>
      <p><input class="product_id" type="text" name="lang">        <select name="choice" class="catalogue">
                <option value="1">Inspirion</option>
                <option value="2">Axpol</option>
                <option value="3">Asgard</option>
                <option value="4">Easy Gifts</option>
                <option value="5">Royal Design</option>
              </select></p>

      <input data-id="{{offer.pk}}" data-href="{% url 'ofertownik:addproduct' %}" type="submit" name="submit" value="Dodaj produkt" class="product_submit">
</form>



{% for each in offer.products.all %}
<a class="btn btn-primary" href="{{each.link}}" target="_blank">Link</a>
<form id="form" method="POST" class="addproduct" style="width:70%;">
  <div class="form-group">
    <label for="">Nazwa</label>
    <input type="text" class="form-control title" value="{{each.name}}" >

  </div>
  <div class="form-group">
    <label for="">Opis</label>
    <textarea class="form-control description" name="name" rows="8" cols="80">{{each.description}}</textarea>

  </div>
  <div class="form-group">
    <label for="">Cena</label>
    <input type="text" class="form-control price" value="{{each.price}}" >

  </div>
  <div class="form-group">
    <label for="">Materiał</label>
    <input type="text" class="form-control material" value="{{each.material}}" >

  </div>
  <div class="form-group">
    <label for="">Rozmiar</label>
    <input type="text" class="form-control size" value="{{each.size}}" >

  </div>
  <!-- <div class="form-group">
    <label for="">Obrazki</label>
    <textarea class="form-control" name="name" rows="8" cols="80">{% for r in each.images.all %}{{r.adress}};
{% endfor %}</textarea> -->

  <!-- </div> -->
<div class="images">
  {% for r in each.images.all %}
<div class="inline-image">


  <img src="{{r.adress}}" class="smolimg" alt="">
 <a href="{{r.adress}}" class="icon"><i class="fas fa-link"></i></a>
  <a href="{% url 'ofertownik:deleteimage' pk=r.pk %}" class="icon"><i class="fas fa-trash"></i></a>
</div>
{% endfor %}
</div>
<div class="">


<button class="deleteproduct" data-href="{% url 'ofertownik:deleteproduct' %}" type="button" data-id="{{each.pk}}" name="button">usuń produkt</button>
<button data-id="{{each.pk}}" data-href="{% url 'ofertownik:editproduct' %}" type="submit" name="submit"  class="editproduct">zapisz produkt</button>

</div>
</form>

<form id="form" method="POST" class="addproducts">
  {% csrf_token %}

        <div class="">
          add image
        </div>
      <p><input class="image_adress" type="text" name="lang"></p>

      <input data-id="{{each.pk}}" data-href="{% url 'ofertownik:addimage' pk=each.pk %}" type="submit" name="submit" value="Dodaj obrazek" class="image_submit">
</form>




  {% endfor %}





<script type="text/javascript">



</script>
{% endblock %}

agmarr/ofertownik/templates/ofertownik/offer_detail.html
{% extends 'base.html' %}
{% block extra_title %}  <title>{{offer.slug}}</title>{% endblock %}
{% block body_block %}



<a href="{% url "index" %}"><img src="http://pphagmar.pl/img/loggo2.png" class="logo" alt=""></a>
<h2>  {{object.title}}</h2>


<div class="chooser">
    <div  id="chcards" class="choose"><i class="fas fa-th-large"></i></div>
  <div  id="chtable" class="choose"><i class="fas fa-th-list"></i></div>

</div>
<div class="cards">


{% for each in object.products.all %}

<div class="card_{{each.pk}} card card0 " id="card__{{each.pk}}" style="width: 15rem;height:600px; vertical-align: top;display:inline-block;">
  <img class="card-img-top" src="{{each.images.first.adress}}" alt="Card image cap">

  <div class="card-body">
    <h5 class="card-title">{{each.name}}</h5>

    <p class="card-text first">{{each.description|truncatewords:25}}</p>
    <p class="card-text"><b>Cena: </b>{{each.price}}</p>
    <div  data-id="{{each.pk}}" class="btn btn-light more" style="  border: 1px solid rgba(0,0,0,.125);  border-radius: .25rem;">Więcej</div>
  </div>
</div>


<div class="card--big big_{{each.pk}}" id="big_{{each.pk}}" >


  <div id="carousel-{{each.pk}}" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      {% for r in each.images.all %}
      <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
        <img class="d-block " src="{{r.adress}}" alt="First slide">
      </div>
      {% endfor %}
    </div>
    <a class="carousel-control-prev" href="#carousel-{{each.pk}}" role="button"  data-slide="prev">
      <span class="carousel-control-prev-icon" style="color: rgba(160, 160, 160, 0.5);" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-{{each.pk}}" role="button" data-slide="next">
      <span class="carousel-control-next-icon" style="color: rgba(160, 160, 160, 0.5);" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

<div class="prod--base">
  <div class="prod--title">
  <h2> {{each.name}}</h2>
  </div>
  <div class="prod--description">
    {{each.description}}
  </div>
</div>
<div class="prod--rest">
  <div class="att prod--price">
    <span class="attlabel">Cena:</span> <span class="attrib">{{each.price}}</span>
  </div>
  <div class="att prod--material">
    <span class="attlabel">Materiał:</span> <span class="attrib">{{each.material}}</span>
  </div>
  <div class="att prod--size">
  <span class="attlabel">Rozmiar:</span>   <span class="attrib">{{each.size}}</span>
  </div>
  <div class="btn btn-light aless" data-id="{{each.pk}}" style="  border: 1px solid rgba(0,0,0,.125);  border-radius: .25rem;">Mniej
  </div>
</div>

</div>
{% endfor %}
</div>
<div class="tabela">
  <table class="tableclass">
{% for each in object.products.all %}
    <tr class="tablemore " id="{{each.pk}}">
      <td class="tabl "><img class="table-img " src="{{each.images.first.adress}}" alt="Card image cap"></td>
      <td class="table-name tabl ">{{each.name}}</td>
      <td class="table-descr tabl ">{{each.description|truncatewords:30}}</td>
      <td class="tabl table-price">{{each.price}}</td>
      <td class="tabl ">    <div  data-id="{{each.pk}}" class="moret btn-light" style="  border: 1px solid rgba(0,0,0,.125);  border-radius: .25rem;"><i class="fas fa-arrows-alt-v"></i></div></td>
    </tr>
    <tr>
<td colspan="5">

      <div class="card--big big_{{each.pk}}" id="big_table_{{each.pk}}" >


        <div id="carousel-table-{{each.pk}}" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            {% for r in each.images.all %}
            <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
              <img class="d-block " src="{{r.adress}}" alt="First slide">
            </div>
            {% endfor %}
          </div>
          <a class="carousel-control-prev" href="#carousel-table-{{each.pk}}" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carousel-table-{{each.pk}}" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

      <div class="prod--base">
        <div class="prod--title">
        <h2> {{each.name}}</h2>
        </div>
        <div class="prod--description">
          {{each.description}}
        </div>
      </div>
      <div class="prod--rest">
        <div class="att prod--price">
          <span class="attlabel">Cena:</span> <span class="attrib">{{each.price}}</span>
        </div>
        <div class="att prod--material">
          <span class="attlabel">Materiał:</span> <span class="attrib">{{each.material}}</span>
        </div>
        <div class="att prod--size">
        <span class="attlabel">Rozmiar:</span>   <span class="attrib">{{each.size}}</span>
        </div>
        <div data-id="{{each.pk}}" class="btn btn-light tless" style="  border: 1px solid rgba(0,0,0,.125);  border-radius: .25rem;">Mniej
        </div>
      </div>
</div>
</td>
    </tr>

{% endfor %}
  </table>

</div>



<script type="text/javascript">
  $( document ).ready(function(){
  $('.card--big').hide();
  $('.card').show();
       $('.tabela').hide();
       $('.fa-th-large').css("border-bottom","2px solid black");
  });

     $(document).on('click','.more',function (e) {
        var pk = $(this).attr("data-id");
        $(this).parents('.card').hide();
        $(".big_"+pk).show();
        document.getElementById("big_"+pk).scrollIntoView();
     });

     $(document).on('click','.aless',function (d) {
        var pk = $(this).attr("data-id");
      document.getElementById('card__'+pk).style.display = "inline-block";
      document.getElementById('big_'+pk).style.display = "none";
     });

     $(document).on('click','.moret',function (e) {
        var pk = $(this).attr("data-id");
        $(this).parents('tr').hide();
        $(".big_"+pk).show();

        document.getElementById("big_"+pk).scrollIntoView();
     });

     $(document).on('click','.tless',function (f) {
        var pk = $(this).attr("data-id");
      document.getElementById(pk).style.display = "table-row";
      document.getElementById('big_table_'+pk).style.display = "none";

     });
     $(document).on('click','#chcards',function () {
       $('.cards').show();
       $('.tabela').hide();
       $('.card--big').hide();
  $('.fa-th-large').css("border-bottom","2px solid black");
  $('.fa-th-list').css("border-bottom","none");
     });
     $(document).on('click','#chtable',function () {
       $('.cards').hide();
       $('.tabela').show();
  $('.card--big').hide();
  $('.fa-th-large').css("border-bottom","none");
  $('.fa-th-list').css("border-bottom","2px solid black");
     });
</script>

{% endblock %}

agmarr/ofertownik/templates/ofertownik/offer_list.html
{% extends 'base.html' %}

{% block body_block %}
{% for each in object_list %}
<a href="{% url 'ofertownik:viewoffer' slug=each.slug %}">{{each.title}}</a><br>
{% endfor %}
{% endblock %}

agmarr/ofertownik/templates/ofertownik/offerform.html
{% extends 'base.html' %}

{% block body_block %}
<form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
</form>
{% endblock %}